### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by TAN-Z-H** [BlockhostOfficial/folia-plugins#36]
很感谢你在GitHub上创建的Folia插件列表项目，我有一个建议，能不能把这些插件的大概功能和用处在列表中新列出一行来展示，以便寻找心仪的插件。再次感谢。

**Comment by Q2297045667** [comment]
这样的话维护起来会很麻烦，而且插件也不多
没必要

**Comment by TAN-Z-H** [comment]
好的
