### ISSUE TITLE
Add ChatControl

### ISSUE THREAD

**Issue by kangarko** [BlockhostOfficial/folia-plugins#41]
ChatControl is a popular chat formatting and filtering plugin, which has recently added support for Folia.

https://builtbybit.com/resources/chatcontrol-red-format-filter-chat.18217/updates#resource-update-105897

-Matej

**Comment by qbasty** [comment]
Done.

**Comment by kangarko** [comment]
Thanks! One small typo, it says "ChatControl**)**". Could you change this to ChatControl Red instead? Appreciate it.
