### ISSUE TITLE
mcMMO

### ISSUE THREAD

**Issue by Hanmingxuan** [BlockhostOfficial/folia-plugins#46]
[Folia Support](https://www.spigotmc.org/resources/official-mcmmo-original-author-returns.64348/update?update=514662)
Folia Support added (Thanks to HSGamer, TechnicallyCoded, Rockyers, and Yomamaeatstoes)

NOTES: This update brings mcMMO to Folia, not all features are guaranteed to work but from limited testing it appears to be working well. Report issues on our GitHub.
https://www.spigotmc.org/resources/official-mcmmo-original-author-returns.64348/update?update=514662

**Comment by qbasty** [comment]
Done.
