### ISSUE TITLE
CmiLib和Residence

### ISSUE THREAD

**Issue by Hanmingxuan** [BlockhostOfficial/folia-plugins#47]
CmiLib和Residence官方已支持folia
那两个连接已失效

**Comment by Hanmingxuan** [comment]
https://www.zrips.net/cmilib/
https://www.spigotmc.org/resources/cmilib.87610/
https://zrips.net/Residence/
https://www.spigotmc.org/resources/residence-1-7-10-up-to-1-20.11480/

**Comment by qbasty** [comment]
Done.
