### ISSUE TITLE
ProtocolLib

### ISSUE THREAD

**Issue by Hanmingxuan** [BlockhostOfficial/folia-plugins#48]
https://github.com/dmulloy2/ProtocolLib/releases

[ProtocolLib v5.1.0](https://github.com/dmulloy2/ProtocolLib/releases/tag/5.1.0) [Latest](https://github.com/dmulloy2/ProtocolLib/releases/latest)
Thank you to my sponsors https://github.com/aternosorg @CJCrafter https://github.com/pebblehost and @GomorrhaDev for their support! Help support the project at https://github.com/sponsors/dmulloy2, it really means a lot :)

What's Changed
Ignore static fields in wrapper class for AutoWrapper by @lukalt in https://github.com/dmulloy2/ProtocolLib/pull/2401
Added method to get RemoteChatSession from player by @lukalt in https://github.com/dmulloy2/ProtocolLib/pull/2406
Cleanup3 by @Photon-GitHub in https://github.com/dmulloy2/ProtocolLib/pull/2414
Correctly resize integer map by @lukalt in https://github.com/dmulloy2/ProtocolLib/pull/2422
Update to 1.20 by @lukalt in https://github.com/dmulloy2/ProtocolLib/pull/2420
Init Folia support by @mani1232 in https://github.com/dmulloy2/ProtocolLib/pull/2346
Fix metrics scheduler for Folia by @lukalt in https://github.com/dmulloy2/ProtocolLib/pull/2449
Added support for dust color transition particles by @RobotHanzo in https://github.com/dmulloy2/ProtocolLib/pull/2455
Implement getNewEntityTracker for Folia by @LOOHP in https://github.com/dmulloy2/ProtocolLib/pull/2464
Some folia fixes by @Anon8281 in https://github.com/dmulloy2/ProtocolLib/pull/2460
FIX wiki.vg uri by @BradBot1 in https://github.com/dmulloy2/ProtocolLib/pull/2480
Full Changelog: https://github.com/dmulloy2/ProtocolLib/compare/5.0.0...5.1.0

**Comment by CJCrafter** [comment]
Hello, I'm not sure what I have to contribute to this issue, but thanks for the mention! 👍

**Comment by Hanmingxuan** [comment]
Init Folia support by @mani1232 in dmulloy2/ProtocolLib#2346
https://github.com/dmulloy2/ProtocolLib/pull/2346

**Comment by Hanmingxuan** [comment]
plugin.yml

folia-supported: true

**Comment by qbasty** [comment]
Done.
