### ISSUE TITLE
Add VelocityVanish

### ISSUE THREAD

**Issue by Syrent** [BlockhostOfficial/folia-plugins#50]
I've just updated my plugin to add Folia support.

Source code: https://github.com/Syrent/VelocityVanish
GitHub releases: https://github.com/Syrent/VelocityVanish/releases
Hangar: https://hangar.papermc.io/Syrent/VelocityVanish
Modrinth: https://modrinth.com/plugin/velocityvanish

**Comment by qbasty** [comment]
Done.
