### ISSUE TITLE
Jobs Reborn 5.2.1.0

### ISSUE THREAD

**Issue by Hanmingxuan** [BlockhostOfficial/folia-plugins#51]
https://www.spigotmc.org/resources/jobs-reborn.4216/updates
[Folia? Kind of.](https://www.spigotmc.org/resources/jobs-reborn.4216/update?update=515059)
**Added initial support for Folia servers**. Update CMILib to the latest version if you are still running older one. This is initial support, so some issues might appear. Report it back to github if you notice any of those.
Changed default behavior for maxjobs in config file. Now for unlimited jobs you will need to set it to -1, while having it at 0 will mean that you can join any jobs. This can be overridden with jobs.max.[amount] permission node. Before having this value at 0 meant that you can join as many jobs as you want, which introduced confusion.
Small fix for limit command output when it comes to bigger numbers.
New bucket action added by FireML
Added feedback message when transferring jobs failed
Now we should keep loading in plugin even if some nonessential file fail to load in due to mis formatting in them.
Fix for sign UI opening in 1.20 servers while interacting with jobs signs
Added support for smithing table, this is mainly for netherite items
Added extra buttons in jobs browse GUI which allows you to join or leave them which will give better feedback for users and are more obvious what to do if you want to join or leave particular job
Small fix for browse main gui window to avoid printing "Press button to join" if you already joined this job
Fix for boost reset command not reset boost if specific job name was provided
Added new command, mainly for staff and debugging, /jobs howmuch which will output possible gain from entity or block you are looking at. This is based on your current jobs and not all of them, includes bonuses. And some actions can't be checked, like item crafting, for obvious reasons. Might be improved later on.

**Comment by qbasty** [comment]
Done.
