### ISSUE TITLE
Add

### ISSUE THREAD

**Issue by HaHaWTH** [BlockhostOfficial/folia-plugins#9]
A fork of AuthMeReloaded with Folia compatibility:
https://github.com/HaHaWTH/AuthMeReReloaded/releases/tag/b10
https://github.com/HaHaWTH/AuthMeReReloaded/

**Comment by HaHaWTH** [comment]
btw the sourcecode has not been commited,but the Folia compatibility is okay

**Comment by HaHaWTH** [comment]
> It says in the release folia compatibility is temporary?

No,i still working on it,and this release can be run on Folia perfectly so i added a temporary label

**Comment by HaHaWTH** [comment]
in the next update i will remove the temporary label

**Comment by qbasty** [comment]
What's up with https://github.com/AuthMe/AuthMeReloaded/pull/2701?

**Comment by HaHaWTH** [comment]
> What's up with [AuthMe/AuthMeReloaded#2701](https://github.com/AuthMe/AuthMeReloaded/pull/2701)?

This PR conflicts with the master branch and it won't be merged,i think,it is hard to add folia compatibility without conflicting with the bukkit API

**Comment by qbasty** [comment]
Merged. Thanks.
